### ISSUE TITLE
Is it possible to post on a group, using a Page name as author AND using facebook-php-sdk?

### ISSUE THREAD

**Issue by JeromeDeBoysere** [janu-software/facebook-php-sdk#10]
Hello,

This is probably not an issue with your great work on facebook-php-sdk, but I found absolutely no answer to my problem, even by reading the Facebook documentation, posting on Stackoverflow or asking on Facebook groups. I think you have more experience with the Facebook SDK and could help me to see more clearly.

All I would to know is : is it possible to create a post on a Facebook group, using a Page name as author (instead of my personal name) and using your Facebook PHP SDK ?

For your information, I'm the admin of the group, of the Page, and of a Facebook API.

Here my detailled issue: https://stackoverflow.com/questions/74748690/how-to-post-on-a-facebook-group-as-a-page-using-graph-explorer-or-php-facebook

Thank you 🙂

**Comment by stanislav-janu** [comment]
Hello,

sorry, but I don't use this feature and I can't help you. :-(

First, request must working in Graph API Explorer. If there works and in SDK no, please tell me about it.

**Comment by JeromeDeBoysere** [comment]
Hi,

Just for you information, it's possible :)
