### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by nightw0lv** [janu-software/facebook-php-sdk#11]
```
public function get(
		string $endpoint,
		$accessToken = null,
		string $eTag = null,
		string $graphVersion = null,
	): Response {
		return $this->sendRequest('GET', $endpoint, $params = [], $accessToken, $eTag, $graphVersion);
	}
```
there are multiple errors like that simplified error line
`public function get(string $endpoint, $accessToken = null, string $eTag = null, string $graphVersion = null, )`
more simplified
`public function get($endpoint, $accessToken = null, $eTag = null, $graphVersion = null, )`
fully simplified
`public function get($graphVersion, )`
public function get($graphVersion **,** ) <- there is an extra coma ","

repeaded typo in files:
Facebook.php,
Application.php
Client.php
/PersistentData/PersistentDataFactory.php
/src/Helper/RedirectLoginHelper.php
/src/Authentication/OAuth2Client.php

some of the catch(type) missing $error var
its php 8+ older versions not work because of type and character |
i would recommend to downgrade to php 7.4+
thank you for this project but wasted my time this typo errors exist since january almost a year ago

**Comment by stanislav-janu** [comment]
There are no typos. This project using strict types and will be. Supports only PHP 8.0+ and will be. If you want something different like support old versions of PHP, feel free to copy and edit project as separate package. Or use original version of SDK [@facebookarchive/php-graph-sdk](https://github.com/facebookarchive/php-graph-sdk) with support PHP 5.3+.
