### ISSUE TITLE
New tag for php 8.2 support

### ISSUE THREAD

**Issue by spointecker** [janu-software/facebook-php-sdk#12]
hey,
could you please tag a new version to get php 8.2 support? :)

**Comment by stanislav-janu** [comment]
Please test dev-main in your project on PHP8.2

**Comment by spointecker** [comment]
Thanks for the hint @stanislav-janu 
Unfortunately the constraint doesnt allow 8.2.1:

`janu-software/facebook-php-sdk dev-main requires php >=8.0 <=8.2 -> your php version (8.2.1) does not satisfy that requirement.`

**Comment by stanislav-janu** [comment]
@spointecker Version 0.1.13 fixed this. Thank you.
