### ISSUE TITLE
Documentation is missing.

### ISSUE THREAD

**Issue by ArtisSkuja** [janu-software/facebook-php-sdk#18]
Hello!
https://github.com/janu-software/facebook-php-sdk/blob/main/docs I was trying to implement this library, but documentation seems to be missing. Thank you!

**Comment by stanislav-janu** [comment]
Hello.
You are right. Docs are missing here. Library is a copy and upgade of original `facebookarchive/php-graph-sdk`.

You can read it on https://github.com/facebookarchive/php-graph-sdk/tree/master/docs in this time.

**Comment by ArtisSkuja** [comment]
Thank you!
