### ISSUE TITLE
?DateTime return type declaration in AccessTokenMetadata->getExpiresAt() method

### ISSUE THREAD

**Issue by frugan-dev** [janu-software/facebook-php-sdk#3]
On some occasions `expires_at = 0`, and this causes an exception:

> JanuSoftware\\Facebook\\Authentication\\AccessTokenMetadata::getExpiresAt(): Return value must be of type ?Safe\\DateTime, int returned

See here https://developers.facebook.com/community/threads/461192667975495/ .

**Comment by JulienRamel** [comment]
@frugan-it I faced the same issue and the fastest option I found was to create a patch to be applied by the Composer Patches module from Cameron Eagans: https://github.com/cweagans/composer-patches.

Here is the patch:

```
diff --git a/vendor/janu-software/facebook-php-sdk/src/Authentication/AccessTokenMetadata.php b/vendor/janu-software/facebook-php-sdk/src/Authentication/AccessTokenMetadata.php
index ab5ab57..ade3dae 100755
--- a/vendor/janu-software/facebook-php-sdk/src/Authentication/AccessTokenMetadata.php
+++ b/vendor/janu-software/facebook-php-sdk/src/Authentication/AccessTokenMetadata.php
@@ -182,7 +182,7 @@ class AccessTokenMetadata
 	/**
 	 * DateTime when this access token expires.
 	 */
-	public function getExpiresAt(): ?DateTime
+	public function getExpiresAt()
 	{
 		return $this->getField('expires_at');
 	}
```

**Comment by frugan-dev** [comment]
Thy @JulienRamel, I had already applied the same patch (but using https://github.com/vaimo/composer-patches), but I still opened an issue hoping that the author will solve it as soon as possible..

**Comment by stanislav-janu** [comment]
Hi, this patch is not strict. My workaround is zero cast as null, because null is non-expiring token like App Token and zero means same.

**Comment by stanislav-janu** [comment]
Test please latest dev-master.

**Comment by frugan-dev** [comment]
LGTM :+1:
