### ISSUE TITLE
How to use with Laravel 9?

### ISSUE THREAD

**Issue by kbs1** [janu-software/facebook-php-sdk#8]
I've been trying to install this package under laravel 9, without success so far.

On a fresh Laravel 9 installation (`composer create-project laravel/laravel test`), when running `composer require janu-software/facebook-php-sdk`, I get:
```
Problem 1
    - Root composer.json requires janu-software/facebook-php-sdk ^0.1.9 -> satisfiable by janu-software/facebook-php-sdk[v0.1.9, 0.1.x-dev].
    - janu-software/facebook-php-sdk[v0.1.9, ..., 0.1.x-dev] require php-http/client-implementation ^1.0 -> could not be found in any version, but the following packages provide it:
 ...
```

Any time I attempt to install any client implementation, for example after `composer require php-http/guzzle7-adapter`, I get:
```
Problem 1
    - Root composer.json requires janu-software/facebook-php-sdk ^0.1.9 -> satisfiable by janu-software/facebook-php-sdk[v0.1.9, 0.1.x-dev].
    - janu-software/facebook-php-sdk[v0.1.9, ..., 0.1.x-dev] require symfony/deprecation-contracts ^2.5 -> found symfony/deprecation-contracts[v2.5.0, v2.5.1, v2.5.2, 2.5.x-dev] but the package is fixed to v3.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```
How to use this package with Laravel 9?

**Comment by kbs1** [comment]
I see it is a known issue - https://github.com/janu-software/facebook-php-sdk/commit/6ac5a8a60afb12a148960f7688142aad8657a26f - will keep an eye on later versions

**Comment by stanislav-janu** [comment]
Try v0.1.10

**Comment by kbs1** [comment]
Hello, this works great after installing `php-http/guzzle7-adapter`, thank you! :)
